#!/bin/python3

import math
import os
import random
import re
import sys



#
# Complete the 'flippingMatrix' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY matrix as parameter.
#

def flippingMatrix(matrix):
    new_row = len(matrix)//2
    new_col = len(matrix[0])//2
    total_sum = 0
    
    for i in range(new_row):
        for j in range(new_col):
            total_sum += max(matrix[i][j], matrix[len(matrix) - 1 - i][len(matrix[0]) - 1 - j], matrix[len(matrix) - 1 - i][j], matrix[i][len(matrix) - 1 - j])
    return total_sum
