#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'lonelyinteger' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY a as parameter.
#

def lonelyinteger(a):
    num_dict = {}
    num_count = 0
    for i in range(len(a)):
        if a[i] in num_dict:
            num_dict[a[i]] += 1
        else:
            num_dict[a[i]] = num_count 
    for ele in num_dict:
        if num_dict[ele] == 1:
            return ele

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    a = list(map(int, input().rstrip().split()))

    result = lonelyinteger(a)

    fptr.write(str(result) + '\n')

    fptr.close()
