#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'isBalanced' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def isBalanced(s):
    pairObjs = {'(':')','{':'}','[':']'}
    matchingPairs = []

    for i in range(len(s)):
        if s[i] in pairObjs:
            matchingPairs.append(pairObjs[s[i]])
        elif s[i] != matchingPairs.pop():
            return 'NO'
    if len(matchingPairs) == 0:
        return 'YES'
       
#second method without runtime errors:
def isBalanced(s):
    pairObjs = {'(':')','{':'}','[':']'}
    matchingPairs = []

    for char in s:
        if char in pairObjs:
            matchingPairs.append(pairObjs[char])
        else:
            if len(matchingPairs) > 0:
                if matchingPairs.pop() != char:
                    return 'NO'
            #if we have nothing but closing brackets or a pair's closing bracket appears first, that's an automatic "no"    
            else: 
                return 'NO'
    if len(matchingPairs) == 0:
        return 'YES'
    else:
        return 'NO'
       
        
            
